services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - PORT=5001
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
    develop:
      watch:
        - action: sync
          path: ./auth-service
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    ports:
      - "5001:5001"

  # Add more services here (e.g., user-service) using the same DB config

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./api-gateway
          target: /src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      - auth-service
